print("This is my file to test Python's execution methods.")
print("The variable __name__ tells me which context this file is running in.")
print("The value of __name__ is:", repr(__name__))
print("The value of __doc__ is:", repr(__doc__))
print("The value of __package__ is:", repr(__package__))
